### PR TITLE
Expanding to other yolo models

### PR DESCRIPTION
**Pull request by IanButterworth**
Currently trying to add YOLOv2.

@Ybakman I don't immediately know how to handle the `[route]` and `[reorg]` layers from YOLOv2.

### CODE REVIEW

**Comment by IanButterworth** [comment]
The specific gaps: https://github.com/ianshmean/YOLO.jl/blob/a3c5c52e1d2e33ebd2fe5f75634b662755be6647/src/models/v2/v2.jl#L107-L114

https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/cfg/yolov2.cfg#L208-L238

**Comment by iuliancioarca** [comment]
Leaving this info here, it might be helpful:
https://github.com/AlexeyAB/darknet/issues/279#issuecomment-397248821
https://github.com/AlexeyAB/darknet/issues/487#issuecomment-374902735
I will dig a little inside Darknet source code these days.

**Comment by IanButterworth** [comment]
@iuliancioarca great, those explanations are really helpful, thanks.

btw, I've disabled CI on cirrus (freebsd) and appveyor (windows) CI, given that Knet requires a compiler for CPU-only `conv` layers, and the default CI images don't have one pre-installed, and it evidently takes too long to install `gcc/g++` on freebsd and it's not clear how one should instal visual studio on the windows instances

**Comment by IanButterworth** [comment]
FreeBSD failures are ImageMagick related https://github.com/JuliaIO/ImageMagick.jl/pull/166

**Comment by IanButterworth** [comment]
YOLOv2 implementation isn't finished, but I'm going to merge as this branch has other improvements that should go to master

**Comment by iuliancioarca** [comment]
Regarding the route layer, I was thinking of creating a custom layer capable of storing the result of whichever intermediate layer we need and then joining it in a similar manner as in the post below. This means the Chain will be split in subchains. Not sure yet how to tap into intermediate layer.
https://discourse.julialang.org/t/flux-concatenate-layers/18877

**Comment by iuliancioarca** [comment]
I had a first trial with the route and reorg layer on a custom, smaller model from one of my side projects. I add the code here, for reference, but I'll fork the repo and try to adapt for YOLOv2.
Please feel free to correct this because I'm not very experienced and I might misunderstand some concepts.
Code:

# Define convolutional layers:
`struct ConvPool; w; b; f; end`
`(c::ConvPool)(x) = pool(c.f.(conv4(c.w, x; padding=1) .+ c.b))`
`ConvPool(w1,w2,cx,cy,f=relu) = ConvPool(param(w1,w2,cx,cy), param0(1,1,cy,1), f);`

`struct Conv; w; b; f; end`
`(c::Conv)(x) = c.f.(conv4(c.w, x; padding=1) .+ c.b)`
`Conv(w1,w2,cx,cy,f=relu) = Conv(param(w1,w2,cx,cy), param0(1,1,cy,1), f);`
# Define dense layer:
`struct Dense; w; b; f; end`
`(d::Dense)(x) = d.f.(d.w * mat(x) .+ d.b)`
`Dense(i::Int,o::Int,f=relu) = Dense(param(o,i), param0(o), f);`
# Define a basic chain of layers:
`struct Chain; layers; Chain(args...)=new(args); end`
`(c::Chain)(x) = (for l in c.layers; x = l(x); end; x)`
# Define a custom chain of layers:
`struct Chain_layers; layers; Chain_layers(args...)=new(args); end`

`function (c::Chain_layers)(img)`
`       res_1_2    = c.layers[1](img)`
`	res_2_20   = c.layers[2](res_1_2)`
`	res_reorg  = reorg(res_1_2, 2) # stride is 2`
`	res_concat = concat(res_reorg,res_2_20)`
`	res_3_4    = c.layers[3](res_concat)`
`end`

`(c::Chain_layers)(x,y) = nll(c(x),y)`

`concat(x,y) = (res = cat(x,y,dims=3))`

`function reorg(x,stride)`
`    d1,d2,nr_filt,nr_batch = size(x)`
`    reshape(x,div(d1,stride),div(d2,stride),nr_filt*(stride^2),nr_batch)`
`end`

# Init the model:

`ch_1_2 = Chain(ConvPool(3,3,nr_channels,2), # input is 32x32x1, output is 16x16*2`
`		Conv(3,3,2,2)) # input is 16x16x2, output is 16x16*2`

`		ch_2_20 = Chain(ConvPool(3,3,2,4),  # input is 16x16x2, output is 8x8*4`
`		Conv(3,3,4,4)) # input is 8x8x4, output is 8x8*4`

`		ch_3_4 = Chain(Conv(3,3,12,16), # input is 8x8x12(after reorg and concat), output is 8x8*16`
`		Conv(3,3,16,16), # input is 8x8x16, output is 8x8*16`
`		Dense(1024,128),`
`		Dense(128,60,identity))`

`		model = Chain_layers(ch_1_2, ch_2_20, ch_3_4) # actually concat first two chains and chain with the third`

# Training snippet( not full code, will not work here):
`	    progress!(adam(model, repeat(dtrn,1);lr=lr0))`
`	    acc = accuracy(model, dtst)`

With the full local code I managed to train this model (it doesn't use anchor boxes, so the loss function is plain and simple...).
I named the "route" layer as "concat", and this is responsible for concatenating the outputs of two layers (after passing them through "reorg", for the dims to match).
The "route" layer with a single parameter from darknet is not needed, since I defined a chain ("ch_2_20 ") specifically for processing the result of first chain ("ch_1_2 ").  After that I use "reorg" to reshape the result of "ch_1_2 " in order to "concat" it with the result of "ch_2_20 ". This intermediate result goes into "ch_3_4 ".
I'm not yet sure if my implementation of "reorg" iterates through the feature map and reshapes correctly.

**Pull request merged**
