### PR TITLE
Stripping back package - A fresh start

### PR DESCRIPTION
**Pull request by IanButterworth**
Based on @ybakman's great progress with https://github.com/Ybakman/YoloV2 I'm going to refactor this package around that work, making it as robust as possible

### CODE REVIEW

**Comment by IanButterworth** [comment]
This isn't yet functional, but it builds, and passes some basic tests, and the relative paths seem ok, so I'm going to merge and do a new PR off master

@ybakman @denizyuret I'm going to keep you in the loop with this all. Thanks for the work to make this package possible

**Comment by stemann** [comment]
Why the change from Flux to Knet? (except from the obvious benefit of building on the work at https://github.com/Ybakman/YoloV2)

**Comment by IanButterworth** [comment]
Apart from that reason, there isn't much.. I basically want to get something working, generalized and testing, and @Ybakman got it working!

In the future I'd love to make it agnostic to Knet or Flux backends, but for now I decided to just simplify to get it working.

A PR would be very welcome to make it support both 👍🏻

**Comment by IanButterworth** [comment]
btw, I branched off the initial work in case it has useful content, for easy access https://github.com/ianshmean/YOLO.jl/tree/initial_work

**Comment by iuliancioarca** [comment]
One other reason would be the better memory management of Knet. I had issues in the past with Flux going OOM when training large(ish) networks (similar to v2_tiny). I appreciate both your and @Ybakman's work on YOLO.  Please let me know how I can help.

**Comment by IanButterworth** [comment]
@iuliancioarca Interesting. As it is, it seems to be working well (pretty fast in my experience).

See what you make of the examples that are now in the master README

**Comment by iuliancioarca** [comment]
Looking good! I tested on Win10, julia 1.1.1. Almost everything from master README worked, apart from `renderResult` which had some undef errors due to Makie functions not being explicitly called (`Scene, FRect, image!, rotate!, poly!, text!`). A quick fix with 'Makie.` also rendered the image:)

**Comment by IanButterworth** [comment]
Great! Would you mind PR-ing those Makie fixes? thanks in advance!

**Pull request merged**
